const assert = require("node:assert/strict");
const { spawn } = require("node:child_process");
const path = require("node:path");
const { chromium } = require("playwright");
const server = spawn(process.execPath, ["scripts/preview.cjs"], {cwd:path.resolve(__dirname,".."),env:{...process.env,PORT:"4176"},stdio:["ignore","pipe","pipe"]});
let browser;
(async()=>{
  await new Promise((resolve,reject)=>{server.stdout.once("data",resolve);server.once("error",reject);});
  browser=await chromium.launch();
  const page=await browser.newPage({viewport:{width:1672,height:941}});
  const errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
  await page.goto("http://localhost:4176");
  await page.waitForSelector('.ribbon-canvas[data-chapter="home"]');
  await page.waitForTimeout(1200);
  const first=await page.locator(".ribbon-canvas").screenshot();
  await page.screenshot({path:'.artifacts/ribbon-home.png'});
  await page.waitForTimeout(1000);
  const second=await page.locator(".ribbon-canvas").screenshot();
  await page.screenshot({path:'.artifacts/ribbon-home-next.png'});
  const changes=await page.evaluate(async urls=>{
    const images=await Promise.all(urls.map(async url=>{const i=new Image();i.src=url;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const ctx=c.getContext('2d');ctx.drawImage(i,0,0);return {data:ctx.getImageData(0,0,c.width,c.height).data,width:c.width};}));
    const difference=(x,y,w,h)=>{let sum=0;for(let row=y;row<y+h;row++)for(let col=x;col<x+w;col++)for(let channel=0;channel<3;channel++){const k=(row*images[0].width+col)*4+channel;sum+=Math.abs(images[0].data[k]-images[1].data[k]);}return sum/(w*h*3);};
    return {face:difference(1180,140,150,210),ribbon:difference(270,585,330,90),suit:difference(1070,480,100,90)};
  },[first,second].map(b=>`data:image/png;base64,${b.toString('base64')}`));
  assert.ok(changes.ribbon>1,`Ribbon should visibly flow: ${JSON.stringify(changes)}`);
  assert.ok(changes.face<.05,`Face must remain still: ${changes.face}`);
  assert.ok(changes.suit<.05,`Clothing must remain still: ${changes.suit}`);
  console.log('PASS Visible source-ribbon motion with stationary face and clothing',changes);
  for(const chapter of ['experience','about','contact']){
    await page.locator(`.chapter-nav a[href="#${chapter}"]`).click();
    await page.waitForSelector(`.ribbon-canvas[data-chapter="${chapter}"]`);
    await page.waitForTimeout(1000);
    const before=await page.locator('.ribbon-canvas').screenshot();
    await page.waitForTimeout(600);
    assert.notDeepEqual(await page.locator('.ribbon-canvas').screenshot(),before,`${chapter} ribbon is static`);
    await page.screenshot({path:`.artifacts/ribbon-${chapter}.png`});
  }
  console.log('PASS Experience, About and Contact ribbons flow continuously');
  await page.locator('#motion-toggle').click();
  assert.equal(await page.locator('.ribbon-canvas').count(),0);
  assert.equal(await page.locator('.ribbon-rendered').count(),0);
  await page.locator('#motion-toggle').click();
  await page.waitForSelector('.ribbon-canvas');
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
  assert.equal(await page.locator('.ribbon-canvas').count(),0);
  await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
  await page.waitForSelector('.ribbon-canvas');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForSelector('.ribbon-canvas',{state:'detached'});
  console.log('PASS Pause, hidden document and reduced motion restore stationary source artwork');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:390,height:844});
  await page.locator('.chapter-nav a[href="#home"]').click();
  await page.waitForSelector('.ribbon-canvas[data-chapter="home"]');
  await page.locator('#home').evaluate(el=>el.scrollTop=320);
  await page.screenshot({path:'.artifacts/ribbon-mobile.png'});
  assert.ok(await page.locator('#home').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  console.log('PASS Mobile Intro uses the original separate ribbon with no horizontal overflow');
  assert.deepEqual(errors,[]);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();});
